version: "3"

services:
  redis:
    image: redis:6
    container_name: redis
    restart: always
    env_file:
      - ../default.env
    command: sh -c 'redis-server --requirepass $${REDIS_ROOT_PASSWORD}'
    sysctls:
      - net.core.somaxconn=512
    ports:
      - "6379:6379"