version: '3'
services:
  zookeeper:
    image: zookeeper:3.8
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:3.1
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
