version: '3'

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    restart: always

  nimbus:
    image: storm:2.3
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - "6627:6627"

  supervisor:
    image: storm:2.3
    command: storm supervisor
    volumes:
     - ./storm.yaml:/conf/storm.yaml
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    
  ui:
    image: storm:2.3
    container_name: ui
    command: storm ui
    restart: always
    ports:
      - "49080:8080"
    links: 
      - nimbus
      - zookeeper